---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "metricbeat.fullname" . }}
  labels:
    {{- include "metricbeat.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "metricbeat.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "metricbeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
