---

replicaCount: 1

image:
  repository: docker.io/opensearchproject/logstash-oss-with-opensearch-output-plugin
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

config:
  # LS_JAVA_OPTS to pass to the container. 1g is the default amount of heap.
  javaOpts: "-Xms1g -Xmx1g"

  # Adjust the pipeline batch size and delay as needed. See:
  #   https://www.elastic.co/guide/en/logstash/current/tuning-logstash.html
  pipelineBatchSize: 125
  pipelineBatchDelay: 50

  # Number of pipeline workers, defaults to the CPU cores limit
  # pipelineWorkers: 16

# Logstash inputs and outputs configuration
inputs:
  heartbeat:
    create: false

  beats:
    create: true
    port: 5044
    sslEnabled: false
    # sslCertificateAuthorities:
    #   - '"/usr/share/certs/ca.pem"'
    # sslCertificate: /usr/share/certs/cert.pem
    # sslKey: /usr/share/certs/cert.key

outputs:
  stdout:
    create: false
    codec: rubydebug

  opensearch:
    create: true
    # user: logstash
    # password:
    # index: "%{[@metadata][beat]-%{+YYYY.MM.dd}}"
    # hosts:
    #   - '"http://opensearch:9200"'
    # ssl: false
    # cacert: /usr/share/certs/ca.pem
    # sslCertificateVerification: false

extraVolumes: []

extraVolumeMounts: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  runAsUser: 1000
  # readOnlyRootFilesystem: true

service:
  type: ClusterIP
  ports:
    beats: 5044

resources:
  requests:
    cpu: 2
    memory: 2048Mi
  limits:
    cpu: 4
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity: {}
