apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.beats.type }}
  ports:
    - port: {{ .Values.service.beats.port }}
      targetPort: beats
      protocol: TCP
      name: beats
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "logstash.fullname" . }}-api
  labels:
    {{- include "logstash.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.api.type }}
  ports:
    - port: {{ .Values.service.api.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    {{- include "logstash.selectorLabels" . | nindent 4 }}
