---

replicaCount: 1

image:
  repository: docker.elastic.co/beats/heartbeat
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

config:
  monitors: []
    # - type: http
    #   urls:
    #     - https://my-host.my-domain.my-suffix
    #   schedule: '@every 10s'

  # autodiscover:
  #   providers:
  #     - type: kubernetes
  #       resource: pod
  #       scope: cluster
  #       node: ${NODE_NAME}
  #       hints.enabled: true

outputs:
  logstash:
    create: true
    hosts:
      - '"logstash:5044"'
    ssl:
      enabled: false
      # verificationMode: none
      # certificate: /usr/share/certs/cert.pem
      # key: /usr/share/certs/cert.key
      # certificateAuthorities:
      #  - '"/usr/share/certs/ca.pem"'

extraVolumes: []

extraVolumeMounts: []

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  runAsUser: 0
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
