---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "heartbeat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "heartbeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
