---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heartbeat.fullname" . }}-deployment-config
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
data:
  heartbeat.yml: |-
    # Enable the HTTP metrics endpoint
    http.enabled: true
    http.port: {{ .Values.config.httpPort }}

    {{- with .Values.config.monitors }}
    heartbeat.monitors:
      {{- toYaml . | nindent 6 }}
    {{- end }}

    {{- with .Values.config.autodiscover }}
    heartbeat.autodiscover:
      {{- with .providers }}
      providers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}

    #heartbeat.autodiscover: # Enable one or more of the providers below
    #  providers:
    #    - type: kubernetes
    #      resource: pod
    #      scope: cluster
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #
    #    - type: kubernetes
    #      resource: service
    #      scope: cluster
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #
    #    - type: kubernetes
    #      resource: node
    #      node: ${NODE_NAME}
    #      scope: cluster
    #      templates:
    #        # Example, check SSH port of all cluster nodes:
    #        - condition: ~
    #          config:
    #            - hosts:
    #                - ${data.host}:22
    #              name: ${data.kubernetes.node.name}
    #              schedule: '@every 10s'
    #              timeout: 5s
    #              type: tcp

    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      {{- with .Values.addFields }}
      - add_fields:
          fields:
            {{- toYaml . | nindent 12 }}
      {{- end }}

    {{- if .Values.outputs.logstash.create }}
    output.logstash:
      hosts: [{{ join "," .Values.outputs.logstash.hosts }}]
      {{- if .Values.outputs.logstash.ssl.enabled }}
      ssl.enabled: true
      ssl.verification_mode: "{{ .Values.outputs.logstash.ssl.verificationMode }}"
      ssl.certificate: "{{ .Values.outputs.logstash.ssl.certificate }}"
      ssl.key: "{{ .Values.outputs.logstash.ssl.key }}"
      ssl.certificate_authorities: [{{ join "," .Values.outputs.logstash.ssl.certificateAuthorities }}]
      {{- else }}
      ssl.enabled: false
      {{- end }}
    {{- end }}
