---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "heartbeat.fullname" . }}
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "heartbeat.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "heartbeat.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "heartbeat.serviceAccountName" . }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-c"
            - "/etc/heartbeat.yml"
            - "-e"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          livenessProbe:
            httpGet:
              path: /
              host: 127.0.0.1
              port: {{ .Values.config.httpPort }}
          readinessProbe:
            exec:
              command:
                - /usr/share/heartbeat/heartbeat
                - test
                - output
            # We don't need to run this that often, as this is just for operator help
            periodSeconds: 30
          volumeMounts:
            - name: config
              mountPath: /etc/heartbeat.yml
              readOnly: true
              subPath: heartbeat.yml
            - name: data
              mountPath: /usr/share/heartbeat/data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/heartbeat.yml
              readOnly: true
              subPath: heartbeat.yml
            - name: data
              mountPath: /usr/share/heartbeat/data
            {{- with .Values.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: config
          configMap:
            defaultMode: 0600
            name: {{ include "heartbeat.fullname" . }}-deployment-config
        - name: data
          hostPath:
            # Use a similar path that the ECK operator uses:
            #   https://github.com/elastic/cloud-on-k8s/blob/f130ac0a05c4b398c1591023f1835bb467e1d1dd/pkg/controller/beat/common/pod.go#L35C2-L35C2
            path: /var/lib/{{ .Release.Namespace }}/{{ include "heartbeat.fullname" . }}/heartbeat-data
            type: DirectoryOrCreate
        {{- with .Values.extraVolumes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
