---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heartbeat.fullname" . }}-kubeadm-config
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "heartbeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heartbeat.fullname" . }}-kubeadm-config
  labels:
    {{- include "heartbeat.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "heartbeat.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "heartbeat.fullname" . }}-kubeadm-config
  apiGroup: rbac.authorization.k8s.io
