---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "filebeat.fullname" . }}
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "filebeat.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "filebeat.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

