---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebeat.fullname" . }}-config
  labels:
    {{- include "filebeat.labels" . | nindent 4 }}
data:
  filebeat.yml: |-
    # Enable the HTTP metrics endpoint at localhost:5066
    http.enabled: true

    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

    # To enable hints based autodiscover, remove `filebeat.inputs` configuration and uncomment this:
    #filebeat.autodiscover:
    #  providers:
    #    - type: kubernetes
    #      node: ${NODE_NAME}
    #      hints.enabled: true
    #      hints.default_config:
    #        type: container
    #        paths:
    #          - /var/log/containers/*${data.kubernetes.container.id}.log

    processors:
      - add_cloud_metadata:
      - add_host_metadata:
      {{- with .Values.addFields }}
      - add_fields:
          fields:
            {{- toYaml . | nindent 12 }}
      {{- end }}

    {{- if .Values.outputs.logstash.create }}
    output.logstash:
      hosts: [{{ join "," .Values.outputs.logstash.hosts }}]
      {{- if .Values.outputs.logstash.ssl.enabled }}
      ssl.enabled: true
      ssl.verification_mode: "{{ .Values.outputs.logstash.ssl.verificationMode }}"
      ssl.certificate: "{{ .Values.outputs.logstash.ssl.certificate }}"
      ssl.key: "{{ .Values.outputs.logstash.ssl.key }}"
      ssl.certificate_authorities: [{{ join "," .Values.outputs.logstash.ssl.certificateAuthorities }}]
      {{- else }}
      ssl.enabled: false
      {{- end }}
    {{- end }}
